{% set name = "pyink" %}
{% set version = "24.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyink-{{ version }}.tar.gz
  sha256: 90468db7148bcef7d4ceb3513f75346331f4f61cc13db940d996728602925603

build:
  noarch: python
  entry_points:
    - pyink = pyink:patched_main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.20.0
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - click >=8.0.0
    - mypy_extensions >=0.4.3
    - packaging >=22.0
    - pathspec >=0.9.0
    - platformdirs >=2
    - tomli >=1.1.0
    - typing-extensions >=4.0.1
    - black =={{ version }}

test:
  imports:
    - pyink
  commands:
    - pip check
    - pyink --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/google/pyink
  summary: Pyink is a python formatter, forked from Black with slightly different behavior.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
