{% set name = "pyink" %}
{% set version = "24.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyink-{{ version }}.tar.gz
  sha256: 5ec4339aa4953f796e88d90bcac3e3472161e4c36dbde203d80f5f76721ac718

build:
  noarch: python
  entry_points:
    - pyink = pyink:patched_main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.20.0
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - click >=8.0.0
    - mypy_extensions >=0.4.3
    - packaging >=22.0
    - pathspec >=0.9.0
    - platformdirs >=2
    - tomli >=1.1.0
    - typing-extensions >=4.0.1
    - black =={{ version }}

test:
  imports:
    - pyink
  commands:
    - pip check
    - pyink --help
  requires:
    - pip

about:
  home: https://github.com/google/pyink
  summary: Pyink is a python formatter, forked from Black with slightly different behavior.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
